### ISSUE TITLE
Testing wrong 

### ISSUE THREAD

**Issue by HusainJaffer** [saasbook/hw-sinatra-saas-hangperson#21]
Guessing context 'correctly' says that @valid should return true, then surely context 'incorrectly' should expect that @valid should return false

**Comment by HusainJaffer** [comment]
context 'correctly' do
      before :each do
        @game = HangpersonGame.new('garply')
        @valid = @game.guess('a')
      end
      it 'changes correct guess list' do
        expect(@game.guesses).to eq('a')
        expect(@game.wrong_guesses).to eq('')
      end
      it 'returns true' do
        expect(@valid).not_to be false
      end
    end
    context 'incorrectly' do
      before :each do
        @game = HangpersonGame.new('garply')
        @valid = @game.guess('z')
      end
      it 'changes wrong guess list' do
        expect(@game.guesses).to eq('')
        expect(@game.wrong_guesses).to eq('z')
      end
      it 'returns true' do ###THIS Should be 'returns false'
        expect(@valid).not_to be false ##THIS should be .not_to be true
      end
    end

**Comment by bill-auger** [comment]
@HusainJaffer -

you should notice that further tests require that this method should return false only when a guess is duplicated

if you are a student of the course you should have posted this on the edX forum

if you are a TA of the course you should have discussed this with the other TAs in the slack chat to confirm that this really is a bug - in this case it is not - this is the intended behavior

also thee was no need to duplicate the code that is in this repo when you could have just referenced the file and line number directly as a link - also if you do post code you should format it as a block of code so that it is more4 easily readable
